[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tools"
version = "0.1.0"
dependencies = [
	"feature_engine",
	"scikit-learn",
	"seaborn",
	"statsmodels",
	"toolz",
	"tqdm",
]

[project.optional-dependencies]
catboost = ["catboost"]
lifelines = ["lifelines"]
networkx = ["networkx"]
optuna = ["optuna"]
scikit-survival = ["scikit-survival"]
complete = [
	"catboost", 
	"lifelines", 
	"networkx", 
	"optuna", 
	"scikit-survival",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint] 
select = ["ANN"]
